jobs:
  - job: create_github_release
    steps:
      - task: GithubRelease@0
        inputs:
          action: create
          githubConnection: appiumbot
          repositoryName: appium/WebDriverAgent
          addChangeLog: false
  - template: ./templates/build.yml
    parameters:
      vmImage: 'macOS-11'
      name: 'macOS_11'
      excludeXcode: '10.3.0,10.3,11.3,11.4,12'
