name: Building WebDriverAgent

on:
  workflow_dispatch:

jobs:
  build:
    name: Build WDA for real iOS and tvOS devices
    runs-on: macos-12

    env:
      XCODE_VERSION: 14.1
      ZIP_PKG_NAME_IOS: "WebDriverAgentRunner-Runner.zip"
      PKG_PATH_IOS: "appium_wda_ios"
      ZIP_PKG_NAME_TVOS: "WebDriverAgentRunner_tvOS-Runner.zip"
      PKG_PATH_TVOS: "appium_wda_tvos"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "${{ env.XCODE_VERSION }}"
      - name: Build iOS
        run: |
          xcodebuild clean build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -derivedDataPath $PKG_PATH_IOS \
            -scheme WebDriverAgentRunner \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO ARCHS=arm64
      - name: Creating a zip of WebDriverAgentRunner-Runner.app for iOS
        run: |
          pushd appium_wda_ios/Build/Products/Debug-iphoneos
          zip -r $ZIP_PKG_NAME_IOS WebDriverAgentRunner-Runner.app
          popd
          mv $PKG_PATH_IOS/Build/Products/Debug-iphoneos/$ZIP_PKG_NAME_IOS ./
      - name: Build tvOS
        run: |
          xcodebuild clean build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -derivedDataPath $PKG_PATH_TVOS \
            -scheme WebDriverAgentRunner_tvOS \
            -destination generic/platform=tvOS \
            CODE_SIGNING_ALLOWED=NO ARCHS=arm64
      - name: Creating a zip of WebDriverAgentRunner-Runner.app for tvOS
        run: |
          pushd appium_wda_tvos/Build/Products/Debug-appletvos
          zip -r $ZIP_PKG_NAME_TVOS WebDriverAgentRunner_tvOS-Runner.app
          popd
          mv $PKG_PATH_TVOS/Build/Products/Debug-appletvos/$ZIP_PKG_NAME_TVOS ./
      - name: Upload the built generic app package for iOS
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_IOS }}"
      - name: Upload the built generic app package for tvOS
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_TVOS }}"
